spring:
  application:
    name: user-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka